name: Cypress Tests with Allure Report

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Permet de lancer le workflow manuellement

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Récupérer l'historique précédent depuis gh-pages
      - name: Download history
        uses: actions/checkout@v3
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages
      
      # Préparer les dossiers pour l'historique
      - name: Create history directory
        if: always()
        run: |
          mkdir -p allure-results/history
          mkdir -p allure-history
      
      # Copier l'historique précédent s'il existe
      - name: Copy history from gh-pages
        if: always()
        continue-on-error: true
        run: |
          if [ -d gh-pages/history ]; then
            cp -R gh-pages/history/* allure-results/history/
          fi
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      
      - name: Install dependencies
        run: |
          npm install 
          npx cypress verify
      
      - name: Cache Cypress binary
        uses: actions/cache@v3
        with:
          path: ~/.cache/Cypress
          key: cypress-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            cypress-${{ runner.os }}-

      - name: Verify Cypress
        run: npx cypress verify
        
      - name: Run Cypress tests
        run: npm run cypress:run
        continue-on-error: true  # Continuer même si les tests échouent
      
      - name: Get Allure history
        uses: actions/checkout@v3
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages
      
      - name: Generate Allure Report
        if: always()
        uses: simple-elf/allure-report-action@master
        with:
          allure_results: allure-results
          allure_report: allure-report
          allure_history: allure-history
          keep_reports: 20
          github_run_num: ${{ github.run_number }}
          github_run_id: ${{ github.run_id }}
          allure_generate_args: '--clean'

      # Copier l'historique pour le conserver
      - name: Store history
        if: always()
        run: |
          cp -R allure-history/history allure-report/
      
      - name: Upload Allure report as artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: allure-report
          path: allure-report/
          retention-days: 30
      
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: always() && github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report
          publish_branch: gh-pages
          force_orphan: false